### ISSUE TITLE
Error when running, "Invalid configuration"

### ISSUE THREAD

**Issue by florentdestremau** [TomasVotruba/phpstan-bodyscan#30]
```
Running PHPStan level 0: .

In JsonLoader.php line 22:

  Could not decode JSON from PHPStan: "Invalid configuration:
  The item 'parameters › reportUnmatchedIgnoredErrors' expects to be bool, array given.
  "


In JsonLoader.php line 18:

  Expected JSON to be an array, instead we got: ""


run [--min-level MIN-LEVEL] [--max-level MAX-LEVEL] [--env-file ENV-FILE] [--json] [--bare] [--no-ignore]
```

My phpstan file

```
❯ cat phpstan.neon
includes:
    - phpstan-baseline.neon

parameters:
    level: 6
    reportUnmatchedIgnoredErrors: false
    checkGenericClassInNonGenericObjectType: false
    paths:
        - src
    excludePaths:
        - deploy.php
    tmpDir: .cache/phpstan/
```

The generated phpstan-bodyscan file is indeed weird

```
❯ cat phpstan-bodyscan.neon
includes:
    - phpstan-baseline.neon

parameters:
    level: 6
    reportUnmatchedIgnoredErrors:
        - false
        - false

    checkGenericClassInNonGenericObjectType: false
    paths:
        - src

    excludePaths:
        - deploy.php

    tmpDir: .cache/phpstan/
```
